//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poetry
    {
        public int PoetryID { get; set; }
        public string PoetryName { get; set; }
        public string PoetryContent { get; set; }
        public string PoetryImg { get; set; }
        public Nullable<int> SubsectionID { get; set; }
        public Nullable<int> PoetID { get; set; }
        public Nullable<int> VolumeID { get; set; }
    
        public virtual Poet Poet { get; set; }
        public virtual Subsection Subsection { get; set; }
        public virtual Volume Volume { get; set; }
    }
}
