//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subsection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subsection()
        {
            this.Poetries = new HashSet<Poetry>();
        }
    
        public int SubsectionID { get; set; }
        public string SubsectionName { get; set; }
        public Nullable<int> VolumeID { get; set; }
        public Nullable<int> PoetID { get; set; }
        public Nullable<int> PoetryID { get; set; }
    
        public virtual Poet Poet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poetry> Poetries { get; set; }
        public virtual Volume Volume { get; set; }
    }
}
